CREATE TABLE IF NOT EXISTS item
(
  item_id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_name VARCHAR(255) NOT NULL,
  item_loc VARCHAR(255) NOT NULL,
  item_lent VARCHAR(255) NOT NULL DEFAULT 'No',
  person_name VARCHAR(255) NOT NULL DEFAULT '',
  person_info VARCHAR(255) NOT NULL DEFAULT ''
);--

CREATE TABLE IF NOT EXISTS log
(
  log_id INTEGER PRIMARY KEY AUTOINCREMENT,
  type VARCHAR(255) NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  item_loc VARCHAR(255) NOT NULL,
  person_name VARCHAR(255) NOT NULL,
  person_info VARCHAR(255) NOT NULL,
  stamp DATETIME NOT NULL DEFAULT (DATETIME('NOW', 'LOCALTIME'))
);--
